### ISSUE TITLE
Feature Request: Combined Report

### ISSUE THREAD

**Issue by robphill** [jsteinberg1/CUCM-Phone-Info#10]
Would be super helpful if you had a function that would take the Phone Info and Phone Scrape data and combines them into a single report with the data correlated by endpoint. 

Maybe include a timestamp of the sync and scrape that the data comes from so the user knows how fresh the data is.

**Comment by jsteinberg1** [comment]
I agree, but not sure the best way to do this.   There are so many fields to combine into a single view that it might not be that usable.

**Comment by robphill** [comment]
My feeling is that having too much information is a better problem to have then too little with reporting like this. My guess is users would rather have to filter one CSV file for fields they don't care about then having to drop two CSVs in Excel and writing pivot tables or lookups to get all the data for a single endpoint in one place. 

Sure, some of the fields are duplicated, we could figure that out. But for example, having to correlate serial number to the configuration (from phone scraper output to phone sync output) would require manual data manipulation by the user, when you consider a phone inventory tool, doesn't it make sense to see those two data sets in one view?

**Comment by jsteinberg1** [comment]
I merged the phone info and scraper into a single view as you suggested.  Having the data in two places doesn't really make sense.  The downside is that all phone data is loaded into the browser, for large clusters this can take some time for the browser to load.  I tested with 30k phones and it took about 40 seconds to load on my machine.
