### ISSUE TITLE
Phone Scraper: 8821 CUCM Server not pulled

### ISSUE THREAD

**Issue by robphill** [jsteinberg1/CUCM-Phone-Info#6]
In testing found that the 8821 does not pull the CUCM servers.
This is because the webpage for the 8821 is a little different than say the 8841.
8841 lists 'CUCM server1', 'CUCM server2', etc. for CUCM servers
8821 lists them as 'Server 1', 'Server 2', etc.

**Comment by jsteinberg1** [comment]
can you supply the 'ps_data_collector.py' output for this model as well?

**Comment by robphill** [comment]
[8821-20200512-083429.txt](https://github.com/jsteinberg1/CUCM-Phone-Info/files/4615632/8821-20200512-083429.txt)

**Comment by jsteinberg1** [comment]
should be fixed in latest PS.  please test
