### ISSUE TITLE
Phone Scraper: 7937 Support

### ISSUE THREAD

**Issue by robphill** [jsteinberg1/CUCM-Phone-Info#7]
The 7937 Conference Phones use an entirely different webpage structure than other phones.  
Their URLs are as follows:

Device 	http://<ip_addr>/localmenus.cgi?func=604  
Network 	http://<ip_addr>/localmenus.cgi?func=219
Ethernet 	http://<ip_addr>/localmenus.cgi?func=601
Logging 	http://<ip_addr>/localmenus.cgi?func=603

I can provide you some HTML output from some live to help adapt the tool to pull these. LMK

**Comment by jsteinberg1** [comment]
If you can provide put that would be great.  I posted a script in the lib folder 'ps_data_collector.py' that you can use to collect the data.  If it has sensitive data you can email the file to me at jsteinberg at gmail.com

**Comment by robphill** [comment]
[7937-20200512-083138.txt](https://github.com/jsteinberg1/CUCM-Phone-Info/files/4615633/7937-20200512-083138.txt)

**Comment by jsteinberg1** [comment]
Should be working in latest PS.   I could not find any CDP/LLDP for this model, maybe this is not supported?
