### ISSUE TITLE
Phone Scraper: 6901 Support

### ISSUE THREAD

**Issue by robphill** [jsteinberg1/CUCM-Phone-Info#8]
6901 Phones use a different URL structure than most phone models.
Their URLs are as follows:

Device Information			        http://<ip_addr>/Device_Information.html
Network Setup					http://<ip_addr>/Network_Setup.html
Ethernet Information   			http://<ip_addr>/Ethernet_Information.html
Network  						http://<ip_addr>/Network.html
Device Logs>Status Messages		http://<ip_addr>/Status_Messages.html
Streaming Statistics>Stream 1  	http://<ip_addr>/Stream1.html

I can provide example HTML from some devices for reference if you'd like.

**Comment by jsteinberg1** [comment]
can you supply the 'ps_data_collector.py' output for this model as well?

**Comment by robphill** [comment]
[6901-20200512-082836.txt](https://github.com/jsteinberg1/CUCM-Phone-Info/files/4615637/6901-20200512-082836.txt)

**Comment by jsteinberg1** [comment]
Should be working in latest PS.   I could not find any URLs, ITL, or CDP/LLDP for this model, maybe this is not supported?
