### ISSUE TITLE
Phone Scraper: ATA187 Support

### ISSUE THREAD

**Issue by robphill** [jsteinberg1/CUCM-Phone-Info#9]
Might be helpful to add support for ATA devices to the tool.
I know the ATA-187 has accessible webpages you can scrape.
Their URLs are:

Device Information 					http://<ip_addr>/Device_Information.htm
Network Setup 					http://<ip_addr>/Network_Setup.htm
Network Statistics>Ethernet Information  http://<ip_addr>/Ethernet_Information.htm
Network Statistics>CDP Neighbor  		http://<ip_addr>/CDP_Information.htm
Device Logs>Status Messages  		http://<ip_addr>/Status_Messages.htm
Streaming Statistics>Stream 1  		http://<ip_addr>/RTP1.htm
Streaming Statistics>Stream 2   		http://<ip_addr>/RTP2.htm 
Note those are ***.htm*** NOT ***.html*** files

I can provide example HTML for reference if you'd like to add this support.
I don't have access to any older ATA device models and I believe the newer ones (ATA-190 and ATA191 use authentication to access their web pages by default).

**Comment by jsteinberg1** [comment]
If you can provide put that would be great.  I posted a script in the lib folder 'ps_data_collector.py' that you can use to collect the data.  If it has sensitive data you can email the file to me at jsteinberg at gmail.com

**Comment by robphill** [comment]
[ATA187-20200512-083631.txt](https://github.com/jsteinberg1/CUCM-Phone-Info/files/4615640/ATA187-20200512-083631.txt)

**Comment by jsteinberg1** [comment]
Should be working in latest PS.   I could not find any URLS, ITL, or CDP/LLDP for this model, maybe this is not supported?
